export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_RESET_ERRORS = 'USER_RESET_ERRORS';

export const RESTAURANTS_REQUEST = 'RESTAURANTS_REQUEST';
export const RESTAURANTS_SUCCESS = 'RESTAURANTS_SUCCESS';
export const RESTAURANTS_FAIL = 'RESTAURANTS_FAIL';
export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST';
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS';
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL';
